---
- hosts: apt
  roles:
    - hosts
    - apt
  remote_user: ansible
  become: yes

- hosts: ssh
  roles:
    - ssh
  remote_user: ansible
  become: yes

- hosts: pgsql
  roles:
    - pgsql
  remote_user: ansible
  become: yes
