---
- name: Set the codename to the pgdg_codename translation or the lsb_release, whether it comes first
  set_fact:
    codename: "{{ pgdg_codename[ansible_lsb['codename']] | default(ansible_lsb['codename'])  }}"

- name: Add the postgresql key to the apt repository
  apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc" state=present

- name: add postgresql repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ codename }}-pgdg main"
    state: present

- name: install common packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
  loop: "{{ common_packages|flatten(levels=1) }}"


- name: install postgresql versioned packages
  apt:
    name: "{{ item.0 }}{{ item.1 }}"
    update_cache: yes
    cache_valid_time: 86400
  loop: "{{ pgsql_packages|product(pgsql_versions)|list }}"
