---
- name: build a list of encoding to be installed on the server
  set_fact:
    db_locale: "{{ (db_locale|default([])  +  [item.value.locale|default(default_locale)])|unique }}"
  with_dict: "{{ pg_clusters }}"

- name: Ensure the locale required by the clusters exists
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ db_locale }}"

- name: Build the list of the PostgreSQL defined ports
  set_fact:
    pg_ports: "{{ pg_ports |default([]) + [item.value.params.port] }}"
  with_dict: "{{ pg_clusters }}"

- name: Check the port is unique within the clusters
  assert:
    that: >
          pg_ports | count
          ==
          pg_ports | unique | count
    msg: "Duplicated port detected in the cluster definition. Please check the variable pg_clusters in group_vars or in hosts_vars for any duplicated port."

- name: setup the clusters
  include: setup_clusters.yml
  when: ('dbserver' in group_names) or ('rstserver' in group_names)


- name: deploy pgbackrest.conf
  template:
    src: pgbackrest.conf.j2
    dest: "{{ pgbackrest_conf }}"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0644

- name: setup the backup server
  include: setup_bckserver.yml
  when: ('bckserver' in group_names)
