---
- name: deploy muttrc
  template:
    src: muttrc.j2
    dest: "{{pg_home_dir}}/.muttrc"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0600

- name: Ship the  logrotate configuration for pgbackrest to the backup server
  template:
    src: logrotate_pgbackrest.j2
    dest: "{{ logrotate_pgbackrest }}"
    owner: "root"
    group: "{{ pg_osgroup }}"
    mode: 0644
  when: inventory_hostname in groups['bckserver']

- name: setup the cronjobs for all stanzas on the backup server
  cron: "{{ item }}"
  with_items: "{{cron_config.backup}}"
  when: inventory_hostname in groups['bckserver']

- name: setup the cronjobs for restore test restore server
  cron: "{{ item }}"
  with_items: "{{cron_config.restore}}"
  when: inventory_hostname in groups['rstserver']
